 - name: declare variable at play level
   hosts: all
   connection: local
   vars:
     URL: play.example.com
   tasks:
     - name: Access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}

 - name: declare variable in another file
   hosts: all
   connection: local
   vars_files:
     - var.yml
   tasks:
     - name: Access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}

 - name: declare variable at task level
   hosts: all
   connection: local
   tasks:
     - name: declare and access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}
       vars:
         URL: task.example.com





